=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

fib_A = 1
fib_B = 2
fib_next = 0
sum = 2

while fib_next < 4000000
  fib_next = fib_A + fib_B
  fib_A = fib_B
  fib_B = fib_next
  if fib_next % 2 == 0
      sum = sum + fib_next
  end
end

puts sum
